filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /mnt/g/plotterlogs/*.log
    close_eof: true
    multiline.pattern: '\d{4}-\d{2}-\d{2}.*Creating \d+ plots of size \d+, pool public key'
    multiline.negate: true
    multiline.match: after
    multiline.max_lines: 5000


setup.template.settings:
  index.number_of_shards: 12
  index.number_of_replicas: 0

# output.elasticsearch:
#   hosts: ["localhost:9200"]
output.logstash:
  hosts: ["localhost:5044"]
